name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : jserv
      USER_EMAIL  : jserv.tw@gmail.com
      BOOK_DIR    : .

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3.0.1
    - name: Build and Deploy 🚀
      uses: onejar99/gitbook-build-publish-action@v1.0.2
